---
abstract: 'simple email creation with auto text and html multipart body'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test2::V0: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Email-Simple-Markdown
provides:
  Email::Simple::Markdown:
    file: lib/Email/Simple/Markdown.pm
    version: v0.7.3
  Email::Simple::Markdown::Stuffer:
    file: lib/Email/Simple/Markdown/Stuffer.pm
    version: v0.7.3
requires:
  Carp: '0'
  Email::Abstract: '0'
  Email::MIME: '0'
  Email::Simple: '0'
  Exporter: '0'
  List::Util: '1.29'
  Module::Runtime: '0'
  Moo: '0'
  Moo::Role: '0'
  Role::Tiny: '0'
  Text::MultiMarkdown: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Email-Simple-Markdown/issues
  homepage: https://github.com/yanick/Email-Simple-Markdown
  repository: https://github.com/yanick/Email-Simple-Markdown.git
version: 0.7.3
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributor_covenant:
  version: 0.02
x_contributors:
  - 'Alessandro Ranellucci <aar@cpan.org>'
  - 'Gavin Carr <gavin@openfusion.com.au>'
x_generated_by_perl: v5.30.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
